"""Canonical Risk Engine Schemas and Contracts.

Adapted from teammate's code. Self-contained — no backend imports.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import List, Union
from uuid import UUID

from pydantic import BaseModel, Field


class SignalDirection(str, Enum):
    """Direction of impact on traveller risk profile."""
    INCREASES_RISK = "increases_risk"
    DECREASES_RISK = "decreases_risk"
    NEUTRAL = "neutral"


class SourceModule(str, Enum):
    """Originating subsystem that produced the risk signal."""
    OCR = "ocr"
    MRZ = "mrz"
    VALIDATION = "validation"
    FORENSICS = "forensics"
    FACE = "face"
    CONSISTENCY = "consistency"


class RiskBand(str, Enum):
    """Aggregated risk categorization for human decision-support."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RiskSignal(BaseModel):
    """The universal risk unit produced by all detection modules."""
    case_id: Union[UUID, str] = Field(..., description="Case being screened.")
    signal_name: str = Field(..., description="Standardized signal name.")
    direction: SignalDirection = Field(..., description="Risk direction.")
    magnitude: float = Field(..., ge=0.0, le=1.0, description="Normalized magnitude [0.0, 1.0].")
    explanation: str = Field(..., description="Human-readable explanation.")
    source_module: SourceModule = Field(..., description="Originating subsystem.")


class RiskAssessment(BaseModel):
    """Final aggregated risk profile generated by the Risk Engine."""
    case_id: Union[UUID, str] = Field(..., description="Case identifier.")
    overall_score: float = Field(..., ge=0.0, le=100.0, description="Risk score [0, 100].")
    risk_band: RiskBand = Field(..., description="Risk band.")
    contributing_signals: List[RiskSignal] = Field(default_factory=list, description="Ranked signals.")
    computed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
